### ISSUE TITLE
Display power consumption

### ISSUE THREAD

**Issue by sakalaka8** [IRNAS/arribada-pmp#4]

**Comment by SloMusti** [comment]
Please report the power consumption results here

**Comment by sakalaka8** [comment]
![i2c_display_consumption](https://user-images.githubusercontent.com/43861607/66556923-599f4800-eb51-11e9-9451-58fc8df94951.png)
Average power consumption  of I2C display: 5.20 uA 
Display was measured between Vcc line and GND.
