### ISSUE TITLE
U13 - BME280 fix layout

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/arribada-pmp#7]
THe BME280 sensor does not have a good footprint, GND pad is missing a thermal relief + there must be a mechanical cutout to provide thermal stress relief to the sensor.

**Comment by sakalaka8** [comment]
![slika](https://user-images.githubusercontent.com/43861607/94649424-ef992900-02f4-11eb-84e0-446cea20113a.png)
The BME280 sensor has fixed issues with GND pad around and mechanical cutout.
